### ISSUE TITLE
"Only signed-in users ..." does not force registration on zoom

### ISSUE THREAD

**Issue by daviddumonde** [techies23/video-conference-zoom#3]
From https://wordpress.org/support/topic/only-signed-in-users/#post-8795275

Thanks for looking into it, Deepen.

**Comment by techies23** [comment]
Hi David,

It seems that there an issue on zoom side regarding this feature.. Could you try creating a meeting from https://zoom.us/developer/api/playground and see if it has the same results ? .. If yes then you will need to contact zoom in order to fix this issue.. will be removing this in next update on my side for now.. might add WP system based though ..

Thanx
